name: ci
on: [push]
permissions:
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v14.1
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v10
      with:
        name: opeik
        authToken: ${{ secrets.CACHIX_TOKEN }}
    - if: matrix.os == 'ubuntu-latest'
      run: nix build --print-build-logs .#nixosConfigurations.marisa.config.system.build.toplevel
    - if: matrix.os == 'macos-latest'
      run: nix build --print-build-logs .#darwinConfigurations.reimu.system
